### ISSUE TITLE
Some problems with zoom in sandbox

### ISSUE THREAD

**Issue by Brunobmon** [alexjung/Run-Zoom-in-a-Sandbox#2]
Hi,
I tried to use zoom with firejail by following the guide for ubuntu. I did it in manjaro, and it seemed to work at first. I could login and could use the microphone in the settings, but could not start a call. I can start a call when outside firejail though. Zoom's window title keeps saying connecting, even though I could login. I'm not sure what the problem is. Does anyone have any insight on this?

**Comment by alexjung** [comment]
Unfortunately I have no experience with Manjaro but it could be related to the profile `firejail` is using. Under Ubuntu 18.04 `firejail` comes with a default configuration for Zoom in `/etc/firejail/zoom.profile`. It might be possible that it is configured too restrictive or something like that...

**Comment by Brunobmon** [comment]
Ok, thanks.
