### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by vzaliva** [alexjung/Run-Zoom-in-a-Sandbox#3]
I could not log in with SSO. My zoom account is provided by my university (CMU).
If I try it just says "connecting"

**Comment by vzaliva** [comment]
I've upgraded to use firewjail from ppa and now when I am trying to do SSO login in Zoom it gives me error message: 

"Your Firefox profile cannot be loaded. It may be missing or inaccessible."

I've checked and there is `/etc/firejail/firefox.profile`

**Comment by alexjung** [comment]
After having experienced some problems myself I would rather recommend using the Flatpak version of zoom rather than sandboxing it manually.
