### ISSUE TITLE
no sandboxing of the "apt install"

### ISSUE THREAD

**Issue by Thomas131** [alexjung/Run-Zoom-in-a-Sandbox#4]
Hi!
Thanks for the Tutorial.

From my point of view, the "apt install"-Command outside of the jail ruins the security. The install-script has all privileges ... This may depend on against what scenario you want to protect your device against:
- wanted backdoors by the Zoom-Developers or by the chineese regime
  I assume in a lot of cases, it would be active after install.
- Zoom introducing a auto-start feature enabled by the installer
  It will autostart Zoom unjailed, even without malicious intent
- zoom.us hacked
  The Attacker will probably place the malware in the installer
- Someone abusing accidently placed backdoors
  Here, the installer alone is way less attack surface.

God bless!
Thomas

**Comment by alexjung** [comment]
After some consideration and research I think it would be better to use the Flatpak version of zoom rather than trying to sandbox it manually. But thanks for your comments concerning the different scenarios and where apt could be a problem for them.
