### ISSUE TITLE
Why is the flatpack version better?

### ISSUE THREAD

**Issue by xianwenchen** [alexjung/Run-Zoom-in-a-Sandbox#6]
I'm curious why the flatpack version is better or more secure? Could you perhaps explain it briefly in the README?

**Comment by alexjung** [comment]
With flatpak come advantages like not needing to check if after an update of firejail or Zoom the sandbox configuration still works. Also less experienced users don't have to configure anything with flatpak (or snap for that matter). Moreover, flatpak was built with application isolation in mind while firejail will try to sandbox an application afterwards. So flatpak also serves the dependencies and libraries of Zoom (or any other applications) sandboxed.
I will add some info in the README. Thanks!

**Comment by xianwenchen** [comment]
Thanks!

It seems that flatpak does not use the sandbox function by default. See http://flatkill.org/

**Comment by alexjung** [comment]
Good to know. I also found a thread on reddit concerning [flatpak security](https://www.reddit.com/r/linux/comments/ljbpr9/flatpak_security/).
In the case of Zoom it seems to be at least not as bad as mentioned in your link. As you can see [here](https://github.com/flathub/us.zoom.Zoom/blob/master/us.zoom.Zoom.json#L17) the file system access is restricted. Unfortunately the devices permission apparently needs to be set to `all` for [webcam access](https://docs.flatpak.org/en/latest/sandbox-permissions.html#device-access).
In the reddit thread a tool gets mentioned which might be useful if you want to check flatpak apps' permissions: https://github.com/tchx84/Flatseal

The problem of security updates remains of course - then again the situation is not necessarily much better for old-style system library application distribution depending on the update policy of your distribution of choice...
